### PR TITLE
Fixed glitch where double .add results in a blank prompt

### PR DESCRIPTION
**Pull request by MeijiIshinIsLame**
Hey it's Quade from the server. Wasn't able to test on the bot itself but should be fine.

### CODE REVIEW

**Review by spuuntries — COMMENTED** [review]
What's `thing` here? Idgi, `thing` is replacing a reference to a message content split, why would this work exactly?

**Review by spuuntries — CHANGES_REQUESTED** [review]
Assuming `thing` is `interaction.message.split`, I suggest to change this to a re.sub call instead.

A simple `\.add\s+` is a p good regex from heuristical testing, I'll be adding it to my fork.

For reference: https://github.com/spuuntries/simulakekbot/commit/4f0881678127d0eac80090a69569c13704883685

**Comment by MeijiIshinIsLame** [comment]
Oops...lol. I'll fix in a min.

**Comment by MeijiIshinIsLame** [comment]
closing bc it's included in spuuntries pr and also I did prompt instead of interaction.message.content like a dumbo.

**Pull request closed without merging**
